# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7431687ef99661f19e161a30ac9527fa"
name = "Suavecito Functions"
handle = "suavecito-functions"
application_url = "https://writers-buttons-satisfied-bald.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "subscription-app-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://writers-buttons-satisfied-bald.trycloudflare.com/auth/callback",
  "https://writers-buttons-satisfied-bald.trycloudflare.com/auth/shopify/callback",
  "https://writers-buttons-satisfied-bald.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
