api_version = "2025-07"

[[extensions]]
handle = "delivery-option-hide"
name = "t:name"
description = "t:description"
uid = "e984a3de-5fb0-281c-afa9-8752b5a4d398be70b7ad"
type = "function"

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/delivery-option-hide/:functionId/new"
  details = "/app/delivery-option-hide/:functionId/:id"