api_version = "2025-07"

[[extensions]]
handle = "delivery-option-rename"
name = "t:name"
description = "t:description"
uid = "9bafcddb-5f2f-988c-ef70-17426ae5da6e8d2c1402"
type = "function"

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/delivery-option-rename/:functionId/new"
  details = "/app/delivery-option-rename/:functionId/:id"
