api_version = "2026-10"

[[extensions]]
handle = "buy-x-get-y-product-discount"
name = "t:name"
description = "t:description"
uid = "9f4a81d1-3e7d-d7d9-9d36-70e0cfc6cc0190c9ca72"
type = "function"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/buy-x-get-y-product-discount/:functionId/new"
  details = "/app/buy-x-get-y-product-discount/:functionId/:id"

  [extensions.input.variables]
  namespace = "$app:buy-x-get-y-product-discount"
  key = "selected-collections"
